python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/baidu/bin/udata.bin --threads 1
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/baidu/bin/udata.bin --threads 24
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/california/bin/udata.bin --threads 1
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/california/bin/udata.bin --threads 24
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/cid-patents/bin/udata.bin --threads 1
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/cid-patents/bin/udata.bin --threads 24
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/com-amazon/bin/udata.bin --threads 1
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/com-amazon/bin/udata.bin --threads 24
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/facebook/bin/udata.bin --threads 1
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/facebook/bin/udata.bin --threads 24
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/flickr/bin/udata.bin --threads 1
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/flickr/bin/udata.bin --threads 24
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/higgs/bin/udata.bin --threads 1
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/higgs/bin/udata.bin --threads 24
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/orkut/bin/udata.bin --threads 1
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/orkut/bin/udata.bin --threads 24
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/pokec/bin/udata.bin --threads 1
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/pokec/bin/udata.bin --threads 24
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/socLivejournal/bin/udata.bin --threads 1
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/socLivejournal/bin/udata.bin --threads 24
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/wikipedia/bin/udata.bin --threads 1
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/wikipedia/bin/udata.bin --threads 24
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/twitter2010/bin/udata.bin --threads 1
python benchmark.py --runs 5 --poll 5 --dataset /dfs/scratch0/caberger/datasets/twitter2010/bin/udata.bin --threads 24